conversation/urls.py
from django.urls import path 

from . import views 

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:itemPk>/', views.newConversation, name='new'),
]

core/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('cart/', views.cart, name='cart'),
    path('addToCart/', views.addToCart, name='addToCart'),
    path('removeFromCart/', views.removeFromCart, name='removeFromCart'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/', views.paymentView, name='payment'),
    path('empty_cart/', views.empty_cart, name='empty_cart'),
]

dashboard/urls.py
from django.urls import path 
    
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('cartItemCount/', views.cart_item_count, name='cart_item_count'),
]

onlineMarketPlace/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('ratingsANDreviews/', include('ratingsANDreviews.urls')),
    path('admin/', admin.site.urls),
    path('inbox/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ratingsANDreviews/urls.py
from django.urls import path

from . import views

app_name = 'ratingsANDreviews'

urlpatterns = [
    path('rate/<int:receiverId>/', views.rateUser, name='rateUser'),
    path('review/<int:receiverId>/', views.reviewUser, name='reviewUser'),
    path('user/ratings/', views.userRatings, name='userRatings'),
    # path('user/reviews/', views.userReviews, name='userReviews'),
    path('user/reviews/<int:receiverId>/', views.userReviews, name='userReviews'),
    path('myRatingsAndMyReviews/', views.myRatingsAndMyReviews, name='myRatingsAndMyReviews'),
]

core/models.py
from django.db import models    
from django.contrib.auth.models import User
import uuid

from item.models import Item

# Create your models here.
class Cart(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    
    def __str__(self):
        return str(self.id)
    
    #Calcola il prezzo totale del carrello, sommando il totale_price di ogni elemento nel carrello
    @property
    def totalPrice(self):
        cartItems = self.cartItems.all()
        total = sum([item.item.price * item.quantity for item in cartItems])
        return total
    
    @property
    def numOfItems(self):
        #Calcola il numero totale di elementi nel carrello
        cartItems = self.cartItems.all()
        quantity = sum([item.quantity for item in cartItems])
        return quantity
    
    
class CartItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='itemsCart')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='cartItems')
    quantity = models.IntegerField(default=0)
    
    def __str__(self):
        return self.item.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full px-6 py-4 rounded-xl'
        }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full px-6 py-4 rounded-xl'
        }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full px-6 py-4 rounded-xl'
        }))
        
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm your password',
        'class': 'w-full px-6 py-4 rounded-xl'
        }))
    
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full px-6 py-4 rounded-xl'
        }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full px-6 py-4 rounded-xl'
        }))
        
    

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .models import Cart, CartItem
from .forms import SignupForm
from django.http import JsonResponse
from django.contrib.auth import logout
from django.http import HttpResponseBadRequest
import json
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    items = Item.objects.filter(isSold=False).order_by('-createdAt')[:6]
    categories = Category.objects.all()
    
    cart = None
    
    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
    
    return render(request, 'core/index.html', {
        'items': items,
        'categories': categories,
        'cart': cart,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    # Check if the form is submitted
    if request.method == 'POST':
        # Take all the data from the form and save it to the database
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
         form = SignupForm()
         
    return render(request, 'core/signup.html', {'form': form})

def logoutView(request):
    logout(request)
    return redirect('core:index')  # Redirect to your desired page after logout

def cart(request):
    
    cart = None
    cartItems = []
    
    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
        cartItems = cart.cartItems.all()
        
        # Calcola il prezzo totale per ogni elemento nel carrello
        for cartItem in cartItems:
            cartItem.total_price = cartItem.quantity * cartItem.item.price
    
    context = {'cart': cart, 'cartItems': cartItems}
    
    return render(request, 'core/cart.html', context)

def addToCart(request):
    data = json.loads(request.body)
    item_id = data['id']
    item = Item.objects.get(id=item_id)
    
    cart = None
    numItem = 0
    
    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
        cartitem, created = CartItem.objects.get_or_create(cart=cart, item=item)
        cartitem.quantity += 1
        cartitem.save()
        
        numItem = cart.numOfItems
        
        print(cartitem)
    
    return JsonResponse(numItem, safe=False)


def removeFromCart(request):
    if request.method == 'DELETE':
        data = json.loads(request.body)
        item_id = data['id']
        try:
            cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
            item = Item.objects.get(id=item_id)
            cart_item = CartItem.objects.get(cart=cart, item=item)
            
            if cart_item.quantity > 1:
                cart_item.quantity -= 1
                cart_item.save()
            else:
                cart_item.delete()
            
            cart = Cart.objects.get(user=request.user, completed=False)
            num_items = cart.numOfItems
            
            return JsonResponse(num_items, safe=False)
        
        except (Item.DoesNotExist, CartItem.DoesNotExist):
            return HttpResponseBadRequest("Invalid item ID or cart item does not exist.")
    return HttpResponseBadRequest("Element Removed correctly")


@login_required
def checkout(request):
    cart = None
    cartItems = []

    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
        cartItems = cart.cartItems.all()

    # Calcola il prezzo totale per ogni elemento nel carrello
    for cartItem in cartItems:
        cartItem.total_price = cartItem.quantity * cartItem.item.price

    # Calcola il prezzo totale del carrello
    total_price = sum(cartItem.total_price for cartItem in cartItems)

    context = {'cart': cart, 'cartItems': cartItems, 'total_price': total_price}

    return render(request, 'core/checkout.html', context)

@login_required
def paymentView(request):
    cart = None
    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
    
    context = {
        'cart': cart,
    }
    
    return render(request, 'core/payment.html', context)

@login_required
def empty_cart(request):
    # Recupera il carrello dell'utente attuale
    cart = Cart.objects.get(user=request.user, completed=False)

    # Elimina tutti gli oggetti nel carrello
    CartItem.objects.filter(cart=cart).delete()

    return redirect('core:index')

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <title>{% block title%}{% endblock %} | GAMESMARKET</title>
    </head>

    <body>
        <nav class="px-6 py-6 flex justify-between items-center border-b border-blue-500 bg-black">
            <a href="/" class="text-xl font-semibold text-blue-500">GAMESMARKET</a>

            <div class="space-x-6">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'core:logout' %}" class="text-lg text-red-500 font-semibold hover:text-blue-500">Log out</a>
                {% endif %}
                <a href="{% url 'item:new' %}" class="text-lg text-white font-semibold hover:text-blue-500">New item</a>
                <a href="{% url 'item:items' %}" class="text-lg text-white font-semibold hover:text-blue-500">Search items</a>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'ratingsANDreviews:myRatingsAndMyReviews' %}" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">My ratings/reviews</a>
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-blue-700 text-white rounded-xl hover:bg-blue-900">Dashboard</a>

                    <a href="{% url 'core:cart' %}" class="px-6 py-3 text-lg font-semibold bg-blue-700 text-white rounded-xl hover:bg-blue-900">
                        <span style="font-size: 20px; color: white; padding-right: 0.5rem;"><i class="fas fa-shopping-cart"></i></span>
                        <span id="numOfItems">{{cart.numOfItems}}</span>
                    </a>

                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-blue-700 text-white rounded-xl hover:bg-blue-900">Log in</a>
                {% endif %}
            </div>
        </nav>
        
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="px-6 py-6 flex justify-between bg-black">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-blue-500">GAMESMARKET</h3>
                <p class="text-lg text-white">Buy and sell on the best videogames stuff marketplace: GAMESMARKET!</p>
                <p class="text-lg text-white">Feel the game!</p>
                <p class="text-white font-thin">© 2023 GAMESMARKET</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-blue-500">Menu</h3>
                <ul class="space-y-2">
                    <li> <a href="#" class="text-lg text-white hover:text-blue-700">About</a> </li>
                    <li> <a href="{% url 'core:contact' %}" class="text-lg text-white hover:text-blue-700">Contact</a> </li>
                    <li> <a href="#" class="text-lg text-white hover:text-blue-700">Privacy policy</a> </li>
                    <li> <a href="#" class="text-lg text-white hover:text-blue-700">Terms of use</a> </li>
                </ul>
            </div>
        </footer>

        <script src={% static 'js/script.js' %}></script>
        {% comment %} <script src="{% static 'item/js/itemScript.js' %}"></script> {% endcomment %}
    </body>
<html>

core/templates/core/cart.html
{% extends 'core/base.html' %}

{% block title %}Cart{% endblock %}

{% block content %}
<div class="shoppingCart">
    <h2 class="font-bold bg-blue-600 text-center rounded-xl text-xl p-4">My Cart</h2>

    <div class="grid grid-cols-5 text-center font-bold bg-gray-400 rounded-xl text-xl p-4">
        <div><h4>Image</h4></div>
        <div><h4>Product's Name</h4></div>
        <div><h4>Quantity</h4></div>
        <div><h4>Unit Price</h4></div>
        <div><h4>Price</h4></div>
    </div>

    {% for cartItem in cartItems %}
    <div class="border border-gray-900 rounded-xl">
        <div class="grid grid-cols-5 text-center items-center">
            <div>
                <img src="{{ cartItem.item.image.url }}" alt="{{ cartItem.item.name }}" class="productImage h-16 w-16 mx-auto">
            </div>
            <div>{{ cartItem.item.name }}</div>
            <div>{{ cartItem.quantity }}</div>
            <div>{{ cartItem.item.price }}</div>
            <div class="flex items-center justify-center">
                <span class="mr-2">{{ cartItem.total_price }}</span>
                <button data-item-id="{{ cartItem.item.id }}" onClick= removeFromCart("{{ cartItem.item.id }}") class="flex items-center justify-center bg-transparent border-none outline-none cursor-pointer" id="removeButton">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-4 h-4">
                        <path fill-rule="evenodd" d="M4 5a1 1 0 011-1h10a1 1 0 011 1v1H4V5zm11.293 2H4v8a2 2 0 002 2h8a2 2 0 002-2V7h-2.707zM8 9a1 1 0 00-1 1v5a1 1 0 102 0v-5a1 1 0 00-1-1zm4 0a1 1 0 00-1 1v5a1 1 0 102 0v-5a1 1 0 00-1-1z" clip-rule="evenodd" />
                    </svg>
                </button>
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="font-semibold text-xl border border-gray-900 bg-gray-400 rounded-xl p-2">
        <h1>Total Price: {{ cart.totalPrice }}</h1>
    </div>

    <h2 class="font-bold bg-blue-600 text-center rounded-xl text-xl p-4">
        <div class="flex justify-between">
            <a href="{% url 'item:items' %}" class="px-4 py-2 bg-blue-700 text-white rounded-xl hover:bg-blue-900">Continue shopping -></a>
            <a href="{% url 'core:checkout' %}" class="px-4 py-2 bg-blue-700 text-white rounded-xl hover:bg-blue-900">Checkout</a>
        </div>
    </h2>

</div>
{% endblock %}

core/templates/core/checkout.html
{% extends 'core/base.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}
<div class="flex flex-wrap">
  <!-- Shipping-Form Section -->
  <div class="w-full md:w-2/5">
    <div class="bg-blue-600 rounded-xl p-6">
      <h3 class="text-black mb-4 font-bold">SHIPPING INFORMATION:</h3>
      <form class="grid grid-cols-2 gap-4" id="shipping-form">
        <div id="shippingInfo">
          <div>
            <label for="address" class="block text-white">Address</label>
            <input type="text" id="address" name="address" required class="w-full py-2 px-4 border border-gray-300 rounded-xl focus:outline-none focus:border-blue-700">
          </div>
          <div>
            <label for="city" class="block text-white">City</label>
            <input type="text" id="city" name="city" required class="w-full py-2 px-4 border border-gray-300 rounded-xl focus:outline-none focus:border-blue-700">
          </div>
          <div>
            <label for="state" class="block text-white">State</label>
            <input type="text" id="state" name="state" required class="w-full py-2 px-4 border border-gray-300 rounded-xl focus:outline-none focus:border-blue-700">
          </div>
          <div>
            <label for="zipcode" class="block text-white">Zipcode</label>
            <input type="text" id="zipcode" name="zipcode" pattern="[0-9]{5}" required class="w-full py-2 px-4 border border-gray-300 rounded-xl focus:outline-none focus:border-blue-700" placeholder="Valid zip code (5 number)">
          </div>
        </div>

        <div class="col-span-2 mt-4">
          <div class="flex justify-end">
            <a href="#" onclick="validateForm()" class="bg-blue-700 hover:bg-blue-900 text-white py-2 px-4 rounded-xl cursor-pointer">Continue</a>
          </div>
        </div>
      </form>
    </div>
  </div>

  <!-- White Space Section -->
  <div class="w-full md:w-1/5"></div>

  <!-- Order Summary Section -->
  <div class="w-full md:w-2/5">
    <div class="bg-blue-600 rounded-xl p-6">
      <h3 class="text-white">Order Summary</h3>
      <div class="border border-gray-900 rounded-xl p-4 mt-4">
        <div class="flex justify-between items-center">
          <span class="font-bold">Total Price:</span>
          <span class="font-bold">{{ total_price }}</span>
        </div>
        <hr class="my-2 border-gray-700"> <!-- Linea orizzontale -->
        {% for cartItem in cartItems %}
        <div class="flex justify-between items-center">
          <span>{{ cartItem.item.name }}</span>
          <span>{{ cartItem.item.price }}</span>
        </div>
        <div class="flex justify-between items-center">
          <span>Quantity: {{ cartItem.quantity }}</span>
          <span>Total: {{ cartItem.total_price }}</span>
        </div>
        <hr class="my-2 border-gray-700">
        {% endfor %}
      </div>
    </div>
  </div>
</div>


<script>
function validateForm() {
  var zipcodeInput = document.getElementById("zipcode");
  var zipcodePattern = /^\d{5}$/;
  
  if (!zipcodePattern.test(zipcodeInput.value)) {
    alert("Invalid zip code. Please enter a valid 5-digit zip code.");
    return false;
  }
  
  // Se il codice zip è valido, puoi procedere con il link "Continue"
  window.location.href = "{% url 'core:payment' %}";
}
</script>

{% endblock %}

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>Contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}

    <div class="mt-6 px-6 py-12 bg-blue-600 rounded-xl">
        <h2 class="mb-12 text-2xl text-center font-semibold"> Categories </h2>

        <div class="grid grid-cols-3 gap-3 rounded-xl">
            {% for category in categories %}
                <div>
                    <a href="{% url 'item:items' %}?query=&category={{ category.id }}">
                        <div class="p-6 bg-white rounded-b-xl hover:bg-red-300 rounded-xl">
                            <h2 class="text-xl"> {{ category.name }} </h2>
                            <p class="text-gray-700"> Items: {{ category.items.count }} </p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-blue-600 rounded-xl">
        <h2 class="mb-12 text-2xl text-center font-semibold"> Newest items </h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div> 
                            <img src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-xl"> {{ item.name }} </h2>
                            <p class="text-gray-700"> Category: {{ item.category.name }} </p>
                            <p class="text-gray-700"> Price: {{ item.price }} </p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <script>
        // Quando la pagina viene caricata
        window.addEventListener("DOMContentLoaded", function() {
            // Controlla se l'acquisto è stato effettuato
            var paymentSubmitted = sessionStorage.getItem("paymentSubmitted");
            
            // Verifica se la variabile di stato è impostata su "true"
            if (paymentSubmitted === "true") {
                // Visualizza il popup
                showPopup("Payment successful");
                
                // Resetta la variabile di stato nell'API Web Storage
                sessionStorage.setItem("paymentSubmitted", "false");
            }
        });


        // Funzione per mostrare il popup
        function showPopup(message) {
            // Crea l'elemento del popup
            var popup = document.createElement("div");
            popup.textContent = message;
            popup.style.cssText = `
                position: fixed;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
                padding: 30px;
                background-color: #fff;
                border: 1px solid #ccc;
                border-radius: 4px;
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
                font-size: 18px;
                color: #333;
                z-index: 9999;
            `;

            // Aggiungi il popup al body del documento
            document.body.appendChild(popup);

            // Aggiungi la classe "darken" al body per scurire il resto della pagina
            var darkenBackground = document.createElement("div");
            darkenBackground.style.cssText = `
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background-color: rgba(102, 51, 153, 0.8);
                z-index: 9998;
            `;
            document.body.appendChild(darkenBackground);

            // Rimuovi il popup e lo sfondo scuro dopo un secondo
            setTimeout(function() {
                document.body.removeChild(popup);
                document.body.removeChild(darkenBackground);
                document.body.style.overflow = "";
            }, 1500);

            // Rimuovi il popup e lo sfondo scuro quando viene cliccato
            var removePopup = function() {
                document.body.removeChild(popup);
                document.body.removeChild(darkenBackground);
                document.body.style.overflow = "";
            };

            popup.addEventListener("click", removePopup);
            darkenBackground.addEventListener("click", removePopup);

            // Impedisci lo scrolling della pagina dietro al popup
            document.body.style.overflow = "hidden";
        }

    </script>

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-blue-600 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="mt-2 px-8 py-4 text-lg bg-white text-blue-500 rounded-xl" 
            style="color:blue; background-color:white;" 
            onmouseover="this.style.backgroundColor='cyan';" 
            onmouseout="this.style.backgroundColor='white';">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/payment.html
{% extends 'core/base.html' %}

{% block title %}Payment{% endblock %}

{% block content %}
<div class="flex justify-center">
  <div class="w-full md:w-2/3 lg:w-1/2">
    <div class="bg-blue-600 rounded-xl p-6">
      <h3 class="text-black mb-4 font-bold">PAYMENT INFORMATION:</h3>
      <form id="payment-form" action="{% url 'core:empty_cart' %}" method="POST">
        {% csrf_token %}
        <div>
          <label for="card-number" class="block text-white">Card Number</label>
          <input type="text" id="card-number" name="card-number" pattern="[0-9]{13,19}" required class="w-full py-2 px-4 border border-gray-300 rounded-xl focus:outline-none focus:border-blue-700" placeholder="Enter a valid card number (13-19  number)">
        </div>
        <div>
          <label for="card-holder-name" class="block text-white">Card Holder Name</label>
          <input type="text" id="card-holder-name" name="card-holder-name" required class="w-full py-2 px-4 border border-gray-300 rounded-xl focus:outline-none focus:border-blue-700">
        </div>
        <div>
          <label for="card-holder-surname" class="block text-white">Card Holder Surname</label>
          <input type="text" id="card-holder-surname" name="card-holder-surname" required class="w-full py-2 px-4 border border-gray-300 rounded-xl focus:outline-none focus:border-blue-700">
        </div>
        <div class="grid grid-cols-2 gap-4 mt-4">
          <div>
            <label for="expiration-date" class="block text-white">Expiration Date (MM/YY)</label>
            <input type="text" id="expiration-date" name="expiration-date" pattern="(0[1-9]|1[0-2])\/[0-9]{2}" required class="w-full py-2 px-4 border border-gray-300 rounded-xl focus:outline-none focus:border-blue-700" placeholder="MM/YY">
          </div>
          <div>
            <label for="cvv" class="block text-white">CVV (3 or 4 digits)</label>
            <input type="text" id="cvv" name="cvv" pattern="[0-9]{3,4}" required class="w-full py-2 px-4 border border-gray-300 rounded-xl focus:outline-none focus:border-blue-700" placeholder="CVV">
          </div>
        </div>
        <div class="mt-4">
          <div class="flex justify-end">
            <button id="submit-payment-button" type="submit" class="bg-blue-700 hover:bg-blue-900 text-white py-2 px-4 rounded-xl">Submit Payment</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>


<script>

  // Quando il bottone "Submit Payment" viene premuto
  document.getElementById("submit-payment-button").addEventListener("click", function() {
    // Memorizza la variabile di stato nell'API Web Storage
    sessionStorage.setItem("paymentSubmitted", "true");
  });

</script>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 p-6 mx-auto bg-blue-600 rounded-xl">
        <h1 class="mb-6 text-3xl">Sign up</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1 }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Confirm password</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="mt-2 px-8 py-4 text-lg bg-white text-blue
    -500 rounded-xl" 
                style="color:blue
        ; background-color:white;" 
                onmouseover="this.style.backgroundColor='cyan';" 
                onmouseout="this.style.backgroundColor='white';">Submit</button>
        </form>

    </div>
{% endblock %}