conversation/urls.py
from django.urls import path 

from . import views 

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:itemPk>/', views.newConversation, name='new'),
]

core/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('cart/', views.cart, name='cart'),
    path('addToCart/', views.addToCart, name='addToCart'),
    path('removeFromCart/', views.removeFromCart, name='removeFromCart'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/', views.paymentView, name='payment'),
    path('empty_cart/', views.empty_cart, name='empty_cart'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('cartItemCount/', views.cart_item_count, name='cart_item_count'),
]

onlineMarketPlace/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('ratingsANDreviews/', include('ratingsANDreviews.urls')),
    path('admin/', admin.site.urls),
    path('inbox/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ratingsANDreviews/urls.py
from django.urls import path

from . import views

app_name = 'ratingsANDreviews'

urlpatterns = [
    path('rate/<int:receiverId>/', views.rateUser, name='rateUser'),
    path('review/<int:receiverId>/', views.reviewUser, name='reviewUser'),
    path('user/ratings/', views.userRatings, name='userRatings'),
    # path('user/reviews/', views.userReviews, name='userReviews'),
    path('user/reviews/<int:receiverId>/', views.userReviews, name='userReviews'),
    path('myRatingsAndMyReviews/', views.myRatingsAndMyReviews, name='myRatingsAndMyReviews'),
]

item/models.py
from django.db import models 
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    
    class Meta:
        verbose_name_plural = "Categories"
        ordering = ['name']
        
    def __str__(self):
        return self.name
    
    
class Item(models.Model):
    name = models.CharField(max_length=255)
    # The related_name attribute specifies the name of the reverse relation from the Category model back to your model.
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    
    isSold = models.BooleanField(default=False)
    createdAt = models.DateTimeField(auto_now_add=True)
    
    # The related_name attribute specifies the name of the reverse relation from the User model back to your model.
    createdBy = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

item/forms.py
from django import forms 

from .models import Item

INPUT_CLASSES = 'w-full px-8 py-4 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['category', 'name', 'description', 'price', 'image',]
        
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES,
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES,
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES,
            }), 
        }
        
class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description', 'price', 'image', 'isSold']
        
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES,
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES,
            }), 
        }

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse

from .models import Item, Category
from .forms import NewItemForm, EditItemForm
from core.models import Cart

# Create your views here.
def items(request):
    query = request.GET.get('query', '')
    categories = Category.objects.all()
    categoryId = request.GET.get('category', 0)
    items = Item.objects.filter(isSold=False)
    
    cart = None
    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
    
    if categoryId:
        items = items.filter(category_id=categoryId)
    
    if query:
        # i stays for case insensitive
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    
    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'categoryId': int(categoryId),
        'cart': cart,
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    relatedItems = Item.objects.filter(category=item.category, isSold = False).exclude(pk=pk)[0:3]
    
    cart = None
    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
    
    return render(request, 'item/detail.html',{
        'item': item,
        'relatedItems': relatedItems,
        'cart': cart,
    })
    
@login_required
def new(request):
    cart = None
    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
    
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        
        if form.is_valid():
            # Commit false because we need to add the owner first before saving
            item = form.save(commit=False)
            item.createdBy = request.user
            item.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()
        
        
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New item',
        'cart': cart,
    })
    
@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, createdBy=request.user)
    item.delete()
    
    return redirect('dashboard:index')

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, createdBy=request.user)
    
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        
        if form.is_valid():
            # Commit false because we need to add the owner first before saving
            item = form.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)
        
        
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item',
    })


@login_required
def my_view(request):
    # Logica della vista
    return redirect('item:detail')

@login_required
def cart_item_count(request):
    cart = None
    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
        num_of_items = cart.numOfItems
    else:
        num_of_items = 0

    return JsonResponse({'numOfItems': num_of_items})

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %} {{ item.name }} {% endblock %}

{% block content %}

    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-xl">
        </div>

        <div class="col-span-2 p-6 bg-blue-600 rounded-xl">
            <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
            <p class="text-black"><strong>Category:</strong> {{ item.category.name }} </p>
            <p class="text-black"><strong>Price:</strong> {{ item.price }}</p>
            <p class="text-black"><strong>Seller:</strong> {{ item.createdBy.username }}</p>
            {% if item.description %}
                <p class="text-black"><strong>Description:</strong> <br> {{ item.description }}</p>
            {% endif %}

            {% if request.user == item.createdBy %}
                <div class="mt-6 p-6 bg-white rounded-xl">
                    <p> You are the seller of this item, pay attention... </p>
                    <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Edit</a>
                    <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-600 text-white rounded-xl hover:bg-red-800">Delete</a>
                </div>
            {% else %}
                <div class="addToCartContainer">
                    <button id="refresh-button" onclick="showPopupMessage()" value="{{item.id}}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-white text-blue-600 rounded-xl hover:bg-blue-400">Add to Cart</button>
                </div>
                <div id="popup-message" class=" mt-2 bg-green-500 text-white px-4 py-2 top-4 right-4 rounded-md" style="display: none;">
                    Item successfully added to cart
                </div>

                <div>
                    <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-white text-blue-600 rounded-xl hover:bg-red-300">Contact seller</a>
                </div>
                    
                <div>
                    <a href="{% url 'ratingsANDreviews:rateUser' receiverId=item.createdBy.id  %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-white text-blue-600 rounded-xl hover:bg-green-500">Rate seller.......</a>
                </div>

                <div>
                    <a href="{% url 'ratingsANDreviews:reviewUser' receiverId=item.createdBy.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-white text-blue-600 rounded-xl hover:bg-green-500">Review seller...</a>
                </div> 
            {% endif %}
        </div>

    </div>
        <div class="mt-6 px-6 py-12 bg-blue-600 rounded-xl">
        <h2 class="mb-12 text-2xl text-center"> Related items (same category) </h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in relatedItems %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div> 
                            <img src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl"> {{ item.name }} </h2>
                            <p class="text-gray-500"> Price: {{ item.price }} </p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <script>
        function refreshPage() {
             location.reload();
        }

        function showPopupMessage() {
            const popup = document.getElementById('popup-message');
            popup.style.display = 'block'; // Mostra il messaggio

            setTimeout(() => {
            popup.style.display = 'none'; // Nasconde il messaggio dopo 2 secondi
            refreshPage(); // Ricarica la pagina
            }, 1000);
        }
    </script>

{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

{% comment %} This is the form that will be used to upload the file {% endcomment %}
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 px-8 py-4 text-lg bg-blue-700 hover:bg-blue-900 rounded-xl text-white">Submit</button>
</form>
{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Items{% endblock %}

{% block content %}
    <div class="p-6 grid grid-cols-4 gap-4 bg-blue-600 rounded-xl">

        <div class="col-span-1">
            <form method="get" action="{% url 'item:items' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Type here">

                {% comment %} <button class="mt-2 py-4 px-8 text-lg bg-white text-blue-500 rounded-xl">Search</button> {% endcomment %}
                <button class="mt-2 px-8 py-4 text-lg bg-white text-blue-500 rounded-xl" 
                     style="color:blue; background-color:white;" 
                     onmouseover="this.style.backgroundColor='cyan';" 
                     onmouseout="this.style.backgroundColor='white';">Search</button>
            </form>

            <hr class="my-6">

            <p class="font-semibold">Categories</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == categoryId %} bg-gray-200 {% endif %}">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">

            <p class="font-semibold">Remove filters</p>

            <ul>
                <li><a href="{% url 'item:items' %}" class="mt-2 px-8 py-4 inline-block bg-white text-lg rounded-xl hover:bg-red-500" style="color: blue;">Clear</a></li>
        </div>

        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div> 
                                <img src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-t-xl">
                            </div>

                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl"> {{ item.name }} </h2>
                                <p class="text-gray-500"> Price: {{ item.price }} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>
{% endblock %}